### PR TITLE
Janusz cli phase2 ls

### LINKED ISSUE #224: List CLI command crashes with traceback
```
Traceback (most recent call last):
  File "./bin/pdm", line 10, in <module>
    pdmcli.main(os.path.join(TOP_PATH, "etc", "system.client.conf"))
  File "/home/centos/pdm/src/pdm/CLI/pdmcli.py", line 84, in main
    args.func(args)
  File "/home/centos/pdm/src/pdm/CLI/user_subcommand.py", line 216, in list
    self._print_formatted_listing(listing)
  File "/home/centos/pdm/src/pdm/CLI/user_subcommand.py", line 252, in _print_formatted_listing
    size_len = len(str(max(d['size'] for d in listing)))
  File "/home/centos/pdm/src/pdm/CLI/user_subcommand.py", line 252, in <genexpr>
    size_len = len(str(max(d['size'] for d in listing)))
TypeError: string indices must be integers
```

The input listing dictionary is:
```
{u'gsiftp://pdmtest1.grid.hep.ph.ic.ac.uk:49999/etc/default': [{u'st_ctime': 0, u'st_mtime': 1526649952, u'name': u'.', u'st_nlink': 1, u'st_ino': 0, u'st_dev': 0, u'st_size': 44, u'st_gid': 0, u'st_uid': 0, u'st_mode': 33261, u'st_atime': 0}, {u'st_ctime': 0, u'st_mtime': 1526774048, u'name': u'..', u'st_nlink': 1, u'st_ino': 0, u'st_dev': 0, u'st_size': 8192, u'st_gid': 0, u'st_uid': 0, u'st_mode': 33261, u'st_atime': 0}, {u'st_ctime': 0, u'st_mtime': 1526649952, u'name': u'grub', u'st_nlink': 1, u'st_ino': 0, u'st_dev': 0, u'st_size': 302, u'st_gid': 0, u'st_uid': 0, u'st_mode': 33188, u'st_atime': 0}, {u'st_ctime': 0, u'st_mtime': 1523346843, u'name': u'nss', u'st_nlink': 1, u'st_ino': 0, u'st_dev': 0, u'st_size': 1756, u'st_gid': 0, u'st_uid': 0, u'st_mode': 33188, u'st_atime': 0}, {u'st_ctime': 0, u'st_mtime': 1478283873, u'name': u'useradd', u'st_nlink': 1, u'st_ino': 0, u'st_dev': 0, u'st_size': 119, u'st_gid': 0, u'st_uid': 0, u'st_mode': 33188, u'st_atime': 0}]}
```

It looks like the field names and format have changed quite a lot since the last version...

### PR DESCRIPTION
**Pull request by martynia**
Addresses an issue where CLI crashed because of a different file stat keywords passed over by gfal2. fixes #224 .

### CODE REVIEW

**Comment by martynia** [comment]
I could include constants, if it makes any difference. From the:
https://docs.python.org/3/license.html
you can read:


Note

GPL-compatible doesn’t mean that we’re distributing Python under the GPL. All Python licenses, unlike the GPL, **let you distribute a modified version** without making your changes open source. **The GPL-compatible licenses make it possible to combine Python with other software that is released under the GPL**; the others don’t. 


I don't think we should reinvent the wheel. Making is slightly different (or similar) is a plagiarism. Just add the Python 3 license (8 bullet points) and done.  I think they just wand a brief summary of changes (point 3).

**Comment by sfayer** [comment]
You need to add the full license and a statement of who owns the copyright on the file... I'll leave you to do that. You'll also have to include a LICENSES file at the top level directly stating the main project license (which we haven't picked yet) and state that there is another file in there under a different license.

I didn't suggest changing it slightly... Clearly that is plagiarism. Someone will have to do a clean-room implementation of it if we want to avoid the above.

**Comment by martynia** [comment]
Well, who owns the copyright on the file ? Assuming we only included minor changes (I removed the constants and imported them)

The licence text is obvious

JM

**Comment by martynia** [comment]
I modified the file and added the copyright and the full licence text.

JM

**Pull request merged**
