### PR TITLE
Make Gravatar optional.

### PR DESCRIPTION
**Pull request by alexanderrichards**
There is concern about Gravatar possibly creating shadow profiles about users. This PR give the option to disable the use of Gravatar. This PR fixes https://github.com/ic-hep/pdm/issues/429

@sfayer the name of the config entry is up for discussion. But this is the basic fix.

### CODE REVIEW

**Comment by sfayer** [comment]
Attempting to close and re-open PR to trigger travis because rebuild button is missing...

**Comment by sfayer** [comment]
Want to try rebasing this with the new CI and see if it passes?

**Comment by alexanderrichards** [comment]
will do

**Comment by alexanderrichards** [comment]
success! :tada: The testing not only works it picks up a small bug that I missed!

**Pull request merged**
